import { faAndroid, faApple } from "@fortawesome/free-brands-svg-icons";
import {
  faBuilding,
  faCartShopping,
  faGlobe,
  faColumns,
  faSearch,
  faEnvelope,
  faHandHoldingUsd,
  faChartLine,
  faBullhorn,
  faMobile,
  faVideo,
  faMapMarkerAlt,
  faShoppingCart,
  faCog,
  faRetweet,
  faPrint,
  faLaptop,
  faBox,
  faFileAlt,
  faFlag,
  faPalette,
  faChartBar,
  faImage,
  faBook,
  faTshirt,
  faMapSigns,
  faIdCard,
  faShapes,
  faFilm,
  faCamera,
  faFileSignature,
  faMapMarker,
  faBookOpen,
  faSignature,
  faCommentAlt,
  faHandHoldingHeart,
  faSyncAlt,
  faChartPie,
  faDesktop,
  faCogs,
  faMicrophone,
  faTv,
  faGamepad,
  faDraftingCompass,
  faCheckCircle,
  faWrench,
  faShieldAlt,
  faDollarSign,
  faSearch as faSearchAlt,
  faShoppingBag,
  faTools,
  faCalculator,
  faFileInvoice,
  faBlog,
  faInfoCircle,
  faBriefcase,
  faPhone,
  faCreditCard,
  faRightToBracket,
  faUsers,
  faGaugeHigh,
  faMousePointer,
  faShareNodes,
  faFileLines,
  faMobileScreen,
  faSmile,
  faPenNib,
  faIdBadge,
  faLandmark,
  faScroll,
} from "@fortawesome/free-solid-svg-icons";

export const webDevelopmentLinks = [
  {
    path: "/services/web-development-company/build-business-website",
    title: "Business Websites",
    description:
      "Our business website solutions are designed to drive growth, enhance visibility, and boost profitability in the digital landscape.",
    icon: faBuilding,
  },
  {
    path: "/services/web-development-company/build-ecommerce-website",
    title: "E-commerce",
    description:
      "Elevate your online retail with our bespoke e-commerce solutions. Boost sales, engage customers, and thrive online.",
    icon: faCartShopping,
  },
  {
    path: "/services/web-development-company/website-rebuild",
    title: "Web Revamp",
    description:
      "Transform and modernize your existing website with our web revamp services. Stay ahead and impress your audience.",
    icon: faGlobe,
  },
  {
    path: "/services/web-development-company/control-center-for-business",
    title: "CRM/ERP Panels",
    description:
      "Enhance business operations with our CRM/ERM panels. Streamline processes, manage data, and boost productivity effectively.",
    icon: faColumns,
  },
];

export const mobileappLinks = [
  {
    path: "/services/mobile-app-development-company/mobile-app-design",
    title: "Mobile App Design",
    description: "Creative and user-friendly app design.",
    icon: faPalette,
  },
  {
    path: "/services/mobile-app-development-company/ios-application-development",
    title: "iOS App Development",
    description: "Developing apps for iOS devices.",
    icon: faApple,
  },
  {
    path: "/services/mobile-app-development-company/android-app-development",
    title: "Android App Development",
    description: "Building apps for Android platforms.",
    icon: faAndroid,
  },
  {
    path: "/services/mobile-app-development-company/cross-platform-app-development",
    title: "Cross-Platform App Development",
    description: "Create apps compatible with multiple platforms.",
    icon: faMobileScreen,
  },
  {
    path: "/services/mobile-app-development-company/app-prototyping",
    title: "App Prototyping",
    description: "Prototyping app concepts for validation.",
    icon: faDraftingCompass,
  },
  {
    path: "/services/mobile-app-development-company/app-testing-and-quality-assurance",
    title: "App Testing and Quality Assurance",
    description: "Ensure app quality with rigorous testing.",
    icon: faCheckCircle,
  },
  {
    path: "/services/mobile-app-development-company/app-maintenance-and-support",
    title: "App Maintenance and Support",
    description: "Ongoing maintenance and support services.",
    icon: faWrench,
  },
  {
    path: "/services/mobile-app-development-company/app-security",
    title: "App Security",
    description: "Enhance app security and data protection.",
    icon: faShieldAlt,
  },
  {
    path: "/services/mobile-app-development-company/app-monetization-strategy",
    title: "App Monetization Strategy",
    description: "Strategies for app revenue generation.",
    icon: faDollarSign,
  },
  {
    path: "/services/mobile-app-development-company/app-store-optimization",
    title: "App Store Optimization",
    description: "Optimize apps for better visibility in stores.",
    icon: faSearch,
  },
  {
    path: "/services/mobile-app-development-company/ecommerce-app-development",
    title: "E-commerce App Development",
    description: "Developing apps for e-commerce businesses.",
    icon: faShoppingBag,
  },
];
export const digitalMarketingLinks = [
  {
    path: "/services/digital-marketing-company/search-engine-optimization",
    title: "Search Engine Optimization",
    description: "Optimize your website for search engines.",
    icon: faSearch,
  },
  {
    path: "/services/digital-marketing-company/content-marketing",
    title: "Content Marketing",
    description: "Create and distribute valuable content.",
    icon: faFileLines,
  },
  {
    path: "/services/digital-marketing-company/social-media-marketing",
    title: "Social Media Marketing",
    description: "Promote your brand on social platforms.",
    icon: faShareNodes,
  },
  {
    path: "/services/digital-marketing-company/email-marketing",
    title: "Email Marketing",
    description: "Engage your audience with email campaigns.",
    icon: faEnvelope,
  },
  {
    path: "/services/digital-marketing-company/pay-per-click-advertising",
    title: "Pay-Per-Click Advertising",
    description: "Drive traffic with targeted ads.",
    icon: faMousePointer,
  },
  {
    path: "/services/digital-marketing-company/affiliate-marketing",
    title: "Affiliate Marketing",
    description: "Boost sales through affiliate programs.",
    icon: faHandHoldingUsd,
  },
  {
    path: "/services/digital-marketing-company/analytics-and-data-analysis",
    title: "Analytics and Data Analysis",
    description: "Gain insights from data for better strategies.",
    icon: faChartLine,
  },
  {
    path: "/services/digital-marketing-company/conversion-rate-optimization",
    title: "Conversion Rate Optimization",
    description: "Improve website conversion rates.",
    icon: faGaugeHigh,
  },
  {
    path: "/services/digital-marketing-company/mobile-marketing",
    title: "Mobile Marketing",
    description: "Target users on mobile devices.",
    icon: faMobile,
  },
  {
    path: "/services/digital-marketing-company/video-marketing",
    title: "Video Marketing",
    description: "Use videos for effective marketing.",
    icon: faVideo,
  },
  {
    path: "/services/digital-marketing-company/local-seo-and-marketing",
    title: "Local SEO and Marketing",
    description: "Enhance local online visibility.",
    icon: faMapMarkerAlt,
  },
  {
    path: "/services/digital-marketing-company/ecommerce-marketing",
    title: "Ecommerce Marketing",
    description: "Promote products in online stores.",
    icon: faShoppingCart,
  },
  {
    path: "/services/digital-marketing-company/marketing-automation",
    title: "Marketing Automation",
    description: "Automate marketing tasks for efficiency.",
    icon: faCog,
  },
  {
    path: "/services/digital-marketing-company/remarketing-retargeting",
    title: "Remarketing and Retargeting",
    description: "Re-engage potential customers.",
    icon: faRetweet,
  },
  {
    path: "/services/digital-marketing-company/influencer-marketing",
    title: "Influencer Marketing",
    description: "Collaborate with influencers for promotion.",
    icon: faUsers,
  },
];

export const multimediaLinks = [
  {
    path: "/services/multimedia-company/logo-design",
    title: "Logo Design",
    description: "Create a unique logo for your brand.",
    icon: faPenNib,
  },
  {
    path: "/services/multimedia-company/brand-identity-design",
    title: "Brand Identity Design",
    description: "Build a strong brand identity.",
    icon: faPalette,
  },
  {
    path: "/services/multimedia-company/print-design",
    title: "Print Design",
    description: "Design materials for print.",
    icon: faPrint,
  },
  {
    path: "/services/multimedia-company/web-design",
    title: "Web Design",
    description: "Create stunning websites.",
    icon: faLaptop,
  },
  {
    path: "/services/multimedia-company/user-interface-design",
    title: "User Interface Design",
    description: "Design user-friendly interfaces.",
    icon: faDesktop,
  },
  {
    path: "/services/multimedia-company/user-experience-design",
    title: "User Experience Design",
    description: "Enhance user satisfaction.",
    icon: faSmile,
  },
  {
    path: "/services/multimedia-company/packaging-design",
    title: "Packaging Design",
    description: "Create attractive packaging.",
    icon: faBox,
  },
  {
    path: "/services/multimedia-company/poster-and-flyer-design",
    title: "Poster and Flyer Design",
    description: "Design promotional materials.",
    icon: faFileAlt,
  },
  {
    path: "/services/multimedia-company/brochure-design",
    title: "Brochure Design",
    description: "Design informative brochures.",
    icon: faFileAlt,
  },
  {
    path: "/services/multimedia-company/banner-design",
    title: "Banner Design",
    description: "Design eye-catching banners.",
    icon: faFlag,
  },
  {
    path: "/services/multimedia-company/illustration-services",
    title: "Illustration Services",
    description: "Get custom illustrations.",
    icon: faPalette,
  },
  {
    path: "/services/multimedia-company/infographic-design",
    title: "Infographic Design",
    description: "Create informative infographics.",
    icon: faChartBar,
  },
  {
    path: "/services/multimedia-company/social-media-graphics",
    title: "Social Media Graphics",
    description: "Design graphics for social media.",
    icon: faImage,
  },
  {
    path: "/services/multimedia-company/ebook-and-print-book-cover-design",
    title: "eBook and Print Book Cover Design",
    description: "Design book covers.",
    icon: faBook,
  },
  {
    path: "/services/multimedia-company/t-shirt-and-merchandise-design",
    title: "T-shirt and Merchandise Design",
    description: "Design for apparel and merchandise.",
    icon: faTshirt,
  },
  {
    path: "/services/multimedia-company/signage-and-billboard-design",
    title: "Signage and Billboard Design",
    description: "Create signage and billboards.",
    icon: faMapSigns,
  },
  {
    path: "/services/multimedia-company/business-card-and-stationery-design",
    title: "Business Card and Stationery Design",
    description: "Design business cards and stationery.",
    icon: faIdCard,
  },
  {
    path: "/services/multimedia-company/rendering-and-visualization",
    title: "Rendering and Visualization",
    description: "Create 3D renderings and visualizations.",
    icon: faShapes,
  },
  {
    path: "/services/multimedia-company/motion-graphics-and-animation",
    title: "Motion Graphics and Animation",
    description: "Design motion graphics and animations.",
    icon: faFilm,
  },
  {
    path: "/services/multimedia-company/photo-editing-and-retouching",
    title: "Photo Editing and Retouching",
    description: "Edit and retouch photos.",
    icon: faCamera,
  },
];

export const brandingLinks = [
  {
    path: "/services/branding-comapny/brand-identity-design-exclusive",
    title: "Brand Identity Design Exclusive",
    description: "Exclusive brand identity design services.",
    icon: faIdBadge,
  },
  {
    path: "/services/branding-comapny/brand-logo-design",
    title: "Brand Logo Design",
    description: "Design a unique logo for your brand.",
    icon: faPenNib,
  },
  {
    path: "/services/branding-comapny/brand-guidelines",
    title: "Brand Guidelines",
    description: "Create brand guidelines for consistency.",
    icon: faFileSignature,
  },
  {
    path: "/services/branding-comapny/brand-positioning",
    title: "Brand Positioning",
    description: "Strategically position your brand.",
    icon: faMapMarker,
  },
  {
    path: "/services/branding-comapny/brand-storytelling",
    title: "Brand Storytelling",
    description: "Craft compelling brand stories.",
    icon: faBookOpen,
  },
  {
    path: "/services/branding-comapny/brand-naming",
    title: "Brand Naming",
    description: "Find the perfect name for your brand.",
    icon: faSignature,
  },
  {
    path: "/services/branding-comapny/visual-identity-design",
    title: "Visual Identity Design",
    description: "Design a strong visual identity.",
    icon: faPalette,
  },
  {
    path: "/services/branding-comapny/brand-messaging",
    title: "Brand Messaging",
    description: "Create effective brand messaging.",
    icon: faCommentAlt,
  },
  {
    path: "/services/branding-comapny/brand-experience-design",
    title: "Brand Experience Design",
    description: "Enhance the brand experience.",
    icon: faHandHoldingHeart,
  },
  {
    path: "/services/branding-comapny/brand-awareness-campaigns",
    title: "Brand Awareness Campaigns",
    description: "Run brand awareness campaigns.",
    icon: faBullhorn,
  },
  {
    path: "/services/branding-comapny/rebranding-services",
    title: "Rebranding Services",
    description: "Rebrand your business effectively.",
    icon: faSyncAlt,
  },
  {
    path: "/services/branding-comapny/brand-research-and-analysis",
    title: "Brand Research and Analysis",
    description: "Conduct brand research and analysis.",
    icon: faChartPie,
  },
  {
    path: "/services/branding-comapny/brand-tracking-and-performance-evaluation",
    title: "Brand Tracking and Performance Evaluation",
    description: "Track and evaluate brand performance.",
    icon: faChartLine,
  },
];

export const advertisingLinks = [
  {
    path: "/services/advertising-company/display-advertising",
    title: "Display Advertising",
    description: "Effective display advertising solutions.",
    icon: faDesktop,
  },
  {
    path: "/services/advertising-company/video-advertising",
    title: "Video Advertising",
    description: "Engage with video advertising campaigns.",
    icon: faVideo,
  },
  {
    path: "/services/advertising-company/native-advertising",
    title: "Native Advertising",
    description: "Discover native advertising strategies.",
    icon: faScroll,
  },
  {
    path: "/services/advertising-company/programmatic-advertising",
    title: "Programmatic Advertising",
    description: "Efficient programmatic advertising.",
    icon: faCogs,
  },
  {
    path: "/services/advertising-company/outdoor-advertising",
    title: "Outdoor Advertising",
    description: "Outdoor advertising solutions.",
    icon: faLandmark,
  },
  {
    path: "/services/advertising-company/print-advertising",
    title: "Print Advertising",
    description: "Effective print advertising services.",
    icon: faFileAlt,
  },
  {
    path: "/services/advertising-company/radio-advertising",
    title: "Radio Advertising",
    description: "Reach audiences through radio ads.",
    icon: faMicrophone,
  },
  {
    path: "/services/advertising-company/tv-advertising",
    title: "TV Advertising",
    description: "Impactful TV advertising campaigns.",
    icon: faTv,
  },
  {
    path: "/services/advertising-company/ingame-advertising",
    title: "In-Game Advertising",
    description: "Advertise within video games.",
    icon: faGamepad,
  },
  {
    path: "/services/advertising-company/theater-advertising",
    title: "Theater Advertising",
    description: "Promote in theaters and cinemas.",
    icon: faFilm,
  },
];

export const moreLinks = [
  {
    path: "/services",
    title: "Services",
    description: "Explore our comprehensive range of services.",
    icon: faTools,
  },
  {
    path: "/contactus/calculate",
    title: "Calculate",
    description: "Use our calculator for quick estimates.",
    icon: faCalculator,
  },
  {
    path: "/contactus/getquotation",
    title: "Get Quotation",
    description: "Request a customized quotation.",
    icon: faFileInvoice,
  },
  {
    path: "/blogs",
    title: "Blogs",
    description: "Read our latest insights and articles.",
    icon: faBlog,
  },
  {
    path: "/aboutus",
    title: "About us",
    description: "Learn more about our company and mission.",
    icon: faInfoCircle,
  },
  {
    path: "/Careers",
    title: "Careers",
    description: "Looking for a Job? Join our team.",
    icon: faBriefcase,
  },
  {
    path: "/contactus",
    title: "Contact",
    description: "Get in touch with us.",
    icon: faPhone,
  },
  {
    path: "/custom-payment",
    title: "Quick Pay",
    description: "Quick Custom Payment.",
    icon: faCreditCard,
  },
  {
    path: "/auth/login",
    title: "Login",
    description: "If you are a customer or existing user, please login.",
    icon: faRightToBracket,
  },
];
